"""empty message

Revision ID: 2021_01_12_01
Revises: f8d0316b63c0
Create Date: 2021-01-12 18:21:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2021_01_12_01'
down_revision = 'f8d0316b63c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boat_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boat')
    # ### end Alembic commands ###
