"""empty message

Revision ID: 5b0636b2fd82
Revises: 2021_01_12_01
Create Date: 2021-01-12 21:45:03.441050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0636b2fd82'
down_revision = '2021_01_12_01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boat_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boat')
    # ### end Alembic commands ###
