"""empty message

Revision ID: 72e7a2838b7f
Revises: 9ea3f3be2cea
Create Date: 2021-01-09 19:37:51.672895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e7a2838b7f'
down_revision = '9ea3f3be2cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus')
    # ### end Alembic commands ###
