"""empty message

Revision ID: b254ad413348
Revises: 6ea325285892
Create Date: 2021-01-09 20:01:02.252433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b254ad413348'
down_revision = '6ea325285892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cart_wheels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'cart_wheels')
    # ### end Alembic commands ###
