"""empty message

Revision ID: f8d0316b63c0
Revises: b254ad413348
Create Date: 2021-01-09 20:06:34.453044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d0316b63c0'
down_revision = 'b254ad413348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_name', sa.String(length=200), nullable=True),
    sa.Column('cart_wheels', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rickshaw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rickshaw_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rickshaw')
    op.drop_table('cart')
    # ### end Alembic commands ###
